version: '3.9'

volumes:
    php_crud_app-db-vol:

services:

    # PHPStorm related stuff
    debug:
        image: phpstorm/php-71-apache-xdebug
        ports:
            - "8081:80"
        # TODO fix below
        volumes:
            - ./workshop/07_Debugging:/var/www/html
        environment:
            #For Windows and macOS, replace the line below with `host.docker.internal`, which will automatically resolve to the internal address of the host Docker is running on.
            #For Linux, replace the line below with your hostname, which you can obtain by executing `hostname` in Terminal.
            XDEBUG_CONFIG: remote_host=host.docker.internal
            #For macOS, if you use a local Homebrew php-fpm installation, port `9000` (which is the default debugging port) may become occupied. PhpStorm will remain silent on starting listening for incoming connections. If this is the case, in the Settings | Languages & Frameworks | PHP | Debug, set the Debug port to 9001, and use the following configuration line instead.
            #XDEBUG_CONFIG: remote_host=host.docker.internal, remote_port=9001
    sftp:
        image: phpstorm/sftp-server
        ports:
            - "2022:22"
        volumes:
        #   Uncomment for Windows
         - C:/temp:/home/jetbrains/upload
        #   Uncomment for macOS/Linux
        # - /tmp:/home/jetbrains/upload
        command: jetbrains:jetbrains:1001
    
    mysql:
        image: phpstorm/mysql
        ports:
            - "33056:3306"
        volumes:
            - ./data:/var/lib/mysql

    nginx-server:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./:/php_crud_app

    php_crud_app-db:
        image: 'mariadb:latest'
        volumes:
            - php_crud_app-db-vol:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: php_crud_app
            MYSQL_DATABASE:  php_crud_app
        ports:
            -   3306:3306
        expose:
            -   3306

    phpmyadmin:
        image: phpmyadmin:latest
        restart: unless-stopped
        ports:
            - 8080:80
        environment:
            # we specify that we connect to an arbitrary server with the flag below
            # "arbitrary" means you're able to specify which database server to use on login page of phpmyadmin      
            - PMA_ARBITRARY=1
        depends_on:
          - php_crud_app-db

    php_crud_app:
        build:
            context: ./
            dockerfile: ./php_crud_app.Dockerfile
        working_dir: /php_crud_app
        volumes:
            - ./:/php_crud_app
            - /php_crud_app/vendor/
            # error reporting is suitable for DEV here
            - ./error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        environment:
            MYSQL_HOST: php_crud_app-db
            MYSQL_USER: root
            MYSQL_PASSWORD: php_crud_app
            MYSQL_DB: php_crud_app
        depends_on:
          - php_crud_app-db
